require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'contactsAIC' do
  config = use_native_modules!

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts.podspec" 

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'


  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'


  target 'contactsAICTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'contactsAIC-tvOS' do
  # Pods for contactsAIC-tvOS

  target 'contactsAIC-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
