// import firebase from './db';

// export const addItem = 
//     (id,
//     label,
//     first_name,
//     middle_name,
//     last_name, 
//     nick_name,
//     number1, 
//     number2,
//     number3,
//     email1,
//     email2,
//     address,
//     messenger1,
//     messenger2,
//     social_media1,
//     social_media2,
//     website1,
//     website2,
//     dob,
//     note,
//     company,
//     job_title,
//     work_hour) => {
//     firebase.firestore().collection(`${id}`).add({
//         label: label,
//         first_name: first_name,
//         middle_name: middle_name,
//         last_name: last_name, 
//         nick_name: nick_name,
//         number1: number1, 
//         number2: number2,
//         number3: number3,
//         email1: email1,
//         email2: email2,
//         address: address,
//         messenger1: messenger1,
//         messenger2: messenger2,
//         social_media1: social_media1,
//         social_media2: social_media2,
//         website1: website1,
//         website2: website2,
//         dob: dob,
//         note: note,
//         company: company,
//         job_title: job_title,
//         work_hour: work_hour
//     })
// }