import firebase from "./db";

export const importContactToFirebase = (
  username,
  profile_image,
  profile_image2,
  profile_image3,
  first_name,
  middle_name,
  last_name,
  nick_name,
  addressLable,
  number1,
  number2,
  number3,
  numberArray,
  email1,
  email2,
  emailArray,
  address1,
  addressArray,
  messenger1,
  messenger2,
  messangerArray,
  social_media1,
  social_media2,
  socialMediaArray,
  website1,
  website2,
  websiteArray,
  dob,
  dateArray,
  note,
  noteArray,
  company,
  companyArray,
  job_title,
  work_hour,
  jobTitleArray,
  workHoursArray,
  selectedLable,
  selected,
  r_label_name,
  s_label_name,
  isImport,
  monday,
  mondayTo,
  tuesday,
  tuesdayTo,
  wednesday,
  wednesdayTo,
  thursday,
  thursdayTo,
  friday,
  fridayTo,
  saturday,
  saturdayTo,
  sunday,
  sundayTo,
  user_id,
  unique_id,
  first_name_small,
  middle_name_small
) => {
  firebase
    .firestore()
    .collection("user")
    .doc(`${username}`)
    .collection("contacts")
    .add({
      profile_image: profile_image,
      profile_image2: profile_image2,
      profile_image3: profile_image3,
      // selectedLable:selectedLable,
      first_name: first_name,
      middle_name: middle_name,
      last_name: last_name,
      nick_name: nick_name,
      addressLable: addressLable,
      number1: number1,
      number2: number2,
      number3: number3,
      number: numberArray,
      email1: email1,
      email2: email2,
      email: emailArray,
      address1: addressArray,
      address: address1,
      messenger1: messenger1,
      messenger2: messenger2,
      messenger: messangerArray,
      social_media1: social_media1,
      social_media2: social_media2,
      social_media: socialMediaArray,
      website: website1,
      website2: website2,
      websiteArray: websiteArray,
      date: dob,
      dateArray: dateArray,
      note: note,
      noteArray: noteArray,
      company: company,
      companyArray: companyArray,
      jobTitle: job_title,
      workHours: work_hour,
      jobTitleArray: jobTitleArray,
      workHoursArray: workHoursArray,
      selectedName: selected,
      r_label_name:r_label_name,
      s_label_name:s_label_name,
      isImport: isImport,
      monday : monday,
      mondayTo: mondayTo,
      tuesday: tuesday,
      tuesdayTo: tuesdayTo,
      wednesday: wednesday,
      wednesdayTo: wednesdayTo,
      thursday:thursday,
      thursdayTo:thursdayTo,
      friday: friday,
      fridayTo: fridayTo,
      saturday: saturday,
      saturdayTo: saturdayTo,
      sunday: sunday,
      sundayTo: sundayTo,
      user_id:user_id,
      u_name:first_name,
      unique_id:unique_id,
      first_name_small: first_name_small,
      middle_name_small: middle_name_small,
      last_name_small:"",
      nick_name_small:"",
      // last_name_small: last_name.toLowerCase(),
      // nick_name_small: nick_name.toLowerCase(),
      // isLNUpdate  :false,
      // isFnUpdate : false,
      // isNumberUpdate :false,
      // isNumber2Update : false,
      // isEmailUpdate : false,
      // isEmail2Update :false,
      // isAddressUpdate :false,
      // isAddress2Update : false,
      // isMessengerUpdate :false,
      // isSocialMediaUpdate :false,
      // isWebsiteUpdate :false,
      // isdateUpdate : false,
      // isNoteUpdate :false,
      // isCompanyUpdate : false,
      // isJobTitleUpdate :false,
      // isWorkHoursUpdate : false,
    });
};
