import firebase from "./db";

export const addManualContact = (
  username,
  selectedName,
  profile_image,
  profile_image2,
  profile_image3,
  first_name,
  middle_name,
  last_name,
  nick_name,
  number1,
  number2,
  number3,
  numberArray,
  email1,
  email2,
  emailArray,
  address1,
  address2,
  addressArray,
  messenger1,
  messenger2,
  messangerArray,
  social_media1,
  social_media2,
  socialMediaArray,
  website,
  website2,
  websiteArray,
  date,
    dateArray,
  note,
  noteArray,
  company,
  companyArray,
  job_title,
  work_hour,
  jobTitleArray,
  workHoursArray,
  singleCompany,
  singleWebsite,
  singleMessenger,
  singleSocialMedia,
  singleNote,
  singleJobTitle,
  singleAddress,
  sEmail,
  sNumber,
  sDate,
  unique_id,
  sfirst_name,
  smiddle_name,
 slast_name,
  snick_name,
) => {
  firebase
    .firestore()
    .collection("user")
    .doc(`${username}`)
    .collection("contacts")
    .add({ 
      selectedName :selectedName,
      profile_image: profile_image,
      profile_image2: profile_image2,
      profile_image3: profile_image3,
      first_name: first_name,
      middle_name: middle_name,
      last_name: last_name,
      nick_name: nick_name,
      number11: number1,
      number2: number2,
      number3: number3,
      number: numberArray,
      email11: email1,
      email2: "",
      email: emailArray,
      address: address1,
      address2:address2,
      aAddress: addressArray,
      messenger: messenger1,
      messenger2: messenger2,
      sMessenger: messangerArray,
      social_media: social_media1,
      social_media2: social_media2,
      sSocial_media: socialMediaArray,
      sWebsite: website,
      website2: website2,
      websiteArray : websiteArray,
      sDate: date,
      dateArray: dateArray,
      snote: note,
      noteArray: noteArray,
      sCompany: company,
      companyArray: companyArray,
      sJobTitle: job_title,
      workHours: work_hour,
      jobTitleArray:jobTitleArray,
      workHoursArray:workHoursArray,
      company: singleCompany,
      website: singleWebsite,
      messenger1:singleMessenger,
      social_media1 :singleSocialMedia,
      note :singleNote,
      jobTitle :singleJobTitle,
      address1 :singleAddress,
      isManually : true,
      u_name:first_name,
      r_label_name    :"",
      s_label_name:"",
      email1:sEmail,
      number1 : sNumber,
      date : sDate,
      unique_id:unique_id,
      first_name_small: sfirst_name,
      middle_name_small: smiddle_name,
      last_name_small: slast_name,
      nick_name_small: snick_name,
      monday  :"",
      mondayTo  :"",
      tuesday  :"",
      tuesdayTo  :"",
      wednesday  :"",
      wednesdayTo  :"",
      thursday  :"",
      thursdayTo  :"",
      friday  :"",
      fridayTo  :"",
      saturday  :"",
      saturdayTo  :"",
      sunday  :"",
      sundayTo  :"",
     
    });
};
